// Generated by scripts/gen-icon-overrides.mjs. Do not edit.
// BattleScrolls/ui/journal/utils.lua (abilityIconAbilityIdOverrides).
export const ICON_DONORS: Record<number, number> = {
  227116: 217699, // arcanist's banner (crux pulse) -> banner bearer grimoire
  252143: 217699, // arcanist's banner (ult pulse) -> banner bearer grimoire
  227381: 163896, // spattering disjunction (generic mage icon) -> whirlpool
  201265: 186370, // pragmatic fatecarver shield -> damage
  69118: 63956, // radiant glory heal -> damage
  201275: 183006, // cephaliarch's flail heal -> damage
  45221: 68401, // crafted potion heal -> crown potion heal
  30978: 30973, // essence drain rank 1 heal -> essence drain passive
  45518: 45517, // essence drain rank 2 heal -> essence drain passive
  55606: 55584, // undaunted command rank 1 heal -> undaunted command passive
  55677: 55676, // undaunted command rank 2 heal -> undaunted command passive
  44013: 26305, // Purify heal -> Purify synergy
  41964: 41963, // Blood Feast heal -> Blood Feast synergy
  194645: 183401, // Runeguard of Still Waters heal -> Runeguard of Still Waters active ability
  21908: 21765, // Purifying Light heal -> Purifying Light active ability
  190960: 108098, // Harmony trait heal -> lapidary research passive (harmony itself doesn't have an ability with an icon)
  22225: 22223, // Rite of Passage heal -> Rite of Passage ultimate skill
  22228: 22226, // Practiced Incantation heal -> Practiced Incantation ultimate skill
  22231: 22229, // Remembrance heal -> Remembrance ultimate skill
  39267: 39266, // Soul Shatter Rank 1 damage -> Soul Shatter Rank 1 passive
  45584: 45583, // Soul Shatter Rank 2 damage -> Soul Shatter Rank 2 passive
  107055: 61919, // Merciless Resolve heal -> Merciless Resolve active ability
  52703: 31760, // Light Weaver Ultimate -> Light Weaver passive
  36519: 36514, // mislabeled Rapid Stroke Passive -> Soul Harvest
  61274: 59517, // Bloodspawn Ultimate -> Bloodspawn proc
  108943: 85564, // Nature's Grasp Ultimate (achievement icon) -> active skill
  108945: 85858, // Nature's Embrace Ultimate (achievement icon) -> active skill
  108947: 85859, // Bursting Vines Ultimate (achievement icon) -> active skill
  124166: 118623, // mislabeled Necrotic Potency -> Deaden Pain
  151219: 152673, // Baron Zaudrus Ultimate -> Zaudrus's Ambition stacks
  263621: 263586, // Hold the Line -> Devout Guardian mastery
  267069: 263585, // Missionary of Light -> Bastion of Light mastery
  29474: 29473, // Blessing at the Peak -> Blessing at the Peak
  37233: 32634, // Insatiable Hunger -> Insatiable Hunger
  40495: 40493, // Shooting Star -> Shooting Star
  45146: 36587, // Transfer -> Transfer
  45217: 31744, // Prism -> Prism
  45600: 35800, // Banish the Wicked -> Banish the Wicked
  45620: 39252, // Combat Frenzy -> Combat Frenzy
  86357: 85804, // Enchanted Forest -> Enchanted Forest
  87224: 86135, // Crystallized Shield -> Crystallized Shield
  88513: 86062, // Savage Beast -> Savage Beast
  88771: 86143, // Shimmering Shield -> Shimmering Shield
  120612: 116284, // Corpse Consumption -> Corpse Consumption
  124136: 115238, // Bitter Harvest -> Bitter Harvest
  124192: 118639, // Necrotic Potency -> Necrotic Potency
  185070: 185050, // Implacable Outcome -> Implacable Outcome
  197510: 192515, // Goat -> Goat
  216940: 215731, // Potent Soul -> Sundering Soul
  217512: 217459, // Potent Burst -> Magical Burst
  238144: 238141, // Vengeance Bitter Harvest -> Vengeance Bitter Harvest
  263415: 263412, // Erudite's Rigor -> Erudite's Rigor
  263613: 263603, // Nocturnal Inspiration -> Nocturnal Inspiration
  263689: 263607, // Share the Spoils -> Share the Spoils
  267985: 116284, // Corpse Consumption -> Corpse Consumption
};

// BattleScrolls/core/utils.lua (abilityNameAbilityIdOverrides).
export const NAME_DONORS: Record<number, number> = {
  36519: 36514, // Rapid Stroke Passive -> Soul Harvest
  124166: 118623, // mislabeled Necrotic Potency -> Deaden Pain
  263621: 263586, // Hold the Line -> Devout Guardian
  267069: 263585, // Missionary of Light -> Bastion of Light
};

// BattleScrolls/core/utils.lua (localizedAbilityNameAbilityIdOverrides).
export const LOCALIZED_NAME_DONORS: Record<number, Partial<Record<string, number>>> = {
  195031: { ru: 196775 }, // Crypt Transfer (called U38 Mythic 1 for some reason in Russian) -> Cryptcanon Vestments
};
