export interface PrivacyLink {
  label: string;
  url: string;
}

export interface PrivacyCopy {
  location: string;
  updated: string;
  contact: string;
  sections: { heading: string; body: (string | PrivacyLink)[] }[];
}

const CLOUDFLARE_DPA_URL = "https://www.cloudflare.com/cloudflare-customer-dpa/";
const CLOUDFLARE_PRIVACY_URL = "https://www.cloudflare.com/privacypolicy/";
const IMY_COMPLAINT_URL = "https://www.imy.se/en/individuals/forms-and-e-services/file-a-gdpr-complaint/";

// Keep every translation aligned with the actual service and retention rules.
// Explain what matters to players; keep implementation details in the operations guide.
// Operator details are public contact information supplied by the operator.
export const PRIVACY_OPERATOR = "Vladislav Sheludchenkov";
export const PRIVACY_EMAIL = "v@sheludchenkov.com";
export const PRIVACY_UPDATED = "2026-09-27";

export const PRIVACY_COPY: Record<string, PrivacyCopy> = {
  en: {
    location: "Sweden", updated: "Last updated", contact: "Operator and data controller",
    sections: [
      { heading: "What is uploaded", body: ["Battle Scrolls lets you save and share ESO combat reports online. Uploading is optional; the addon works without it. Reports come from the uploading player’s addon and can include other players’ gamertags or character names, roles, combat statistics, builds, encounter times, in-game locations and custom report titles. The upload also includes the platform and game server."] },
      { heading: "Why data is used", body: ["Data is used to preserve combat history, analyse encounters and share reports. The legal basis is legitimate interests under GDPR Article 6(1)(f): the operator’s and players’ interests in these activities are weighed against the privacy and rights of the people recorded. Limited technical information is also used to run and protect the service, and correspondence is used to handle privacy requests. Uploading a report does not give consent on other players’ behalf. Before uploading, let affected players know about the upload and this notice. There is no advertising, sale of personal data or automated decision-making with legal or similarly significant effects."] },
      { heading: "Who can access data", body: ["Reports do not appear in a public directory or player search. Anyone with a report link can view, download or share it without an account. Cloudflare hosts the service and processes reports and technical information, including IP addresses, to deliver and protect it. IP addresses are not part of combat reports. Cloudflare and its service providers may process data outside the European Economic Area (EEA). Its ", { label: "data processing agreement", url: CLOUDFLARE_DPA_URL }, " provides safeguards for these transfers, including Standard Contractual Clauses where applicable. You can also request a copy of these safeguards by email."] },
      { heading: "How long data is kept", body: ["Reports have no automatic expiry, so you can return to them years later. They are kept while needed for this purpose and while the service operates, subject to justified deletion requests. The need to keep them is reviewed at least once a year. Temporary upload data is normally deleted within two hours. Deleted data may remain in backups for up to 30 days; these copies are not publicly accessible. Privacy correspondence is kept as long as needed to resolve requests and document their handling, with a yearly review. Technical logs are kept for up to seven days. ", { label: "Cloudflare’s privacy policy", url: CLOUDFLARE_PRIVACY_URL }, " explains its own use and retention of data for security purposes."] },
      { heading: "Copies in your browser", body: ["For faster loading, your browser can reuse a saved report for up to one week without checking for changes. Deleting a report cannot immediately remove these copies or any open pages, screenshots or downloads. Your language and pinned-effect preferences are saved in your browser. Upload progress and the resulting link are saved for your browsing session. You can clear these records in your browser. The site does not use advertising or analytics cookies."] },
      { heading: "Your rights and requests", body: ["Email the address above to request access to your data, correction, deletion or restricted use. You can also object to processing based on legitimate interests for reasons related to your particular situation. These rights apply under the conditions set by law. Include your platform, EU/NA game server, current and relevant former gamertags, and report links if you have them; a link is not required. To protect players’ data, you may be asked to confirm that you control the relevant game account. Only information needed for this check will be requested. Do not send passwords or unsolicited identity documents. Requests are handled without undue delay, normally within one month. If a legally permitted extension is needed, you will be told why within that month. You can complain to Sweden’s ", { label: "IMY", url: IMY_COMPLAINT_URL }, " or another competent data protection authority, including where you live or work."] },
    ],
  },
  de: {
    location: "Schweden", updated: "Zuletzt aktualisiert", contact: "Betreiber und Verantwortlicher",
    sections: [
      { heading: "Welche Daten hochgeladen werden", body: ["Mit Battle Scrolls kannst du ESO-Kampfberichte online speichern und teilen. Der Upload ist freiwillig; die Erweiterung funktioniert auch ohne ihn. Berichte stammen aus der Erweiterung des hochladenden Spielers und können Gamertags oder Charakternamen anderer Spieler, Rollen, Kampfstatistiken, Builds, Kampfzeiten, Orte im Spiel und eigene Berichtstitel enthalten. Auch die Plattform und der Spielserver werden übermittelt."] },
      { heading: "Wofür Daten verwendet werden", body: ["Die Daten dienen dazu, den Kampfverlauf aufzubewahren, Kämpfe zu analysieren und Berichte zu teilen. Rechtsgrundlage sind berechtigte Interessen nach Art. 6 Abs. 1 Buchst. f DSGVO: Die Interessen des Betreibers und der Spieler an diesen Tätigkeiten werden gegen die Privatsphäre und Rechte der erfassten Personen abgewogen. Begrenzte technische Informationen dienen außerdem dem Betrieb und Schutz des Dienstes, Korrespondenz der Bearbeitung von Datenschutzanfragen. Ein Upload ersetzt nicht die Einwilligung anderer Spieler. Informiere betroffene Spieler vor dem Upload darüber und über diese Erklärung. Es gibt keine Werbung, keinen Verkauf personenbezogener Daten und keine automatisierten Entscheidungen mit rechtlicher oder ähnlich erheblicher Wirkung."] },
      { heading: "Wer auf Daten zugreifen kann", body: ["Berichte erscheinen weder in einem öffentlichen Verzeichnis noch in einer Spielersuche. Wer den Berichtslink hat, kann den Bericht ohne Konto ansehen, herunterladen oder teilen. Cloudflare hostet den Dienst und verarbeitet Berichte sowie technische Informationen einschließlich IP-Adressen, um ihn bereitzustellen und zu schützen. IP-Adressen sind kein Bestandteil der Kampfberichte. Cloudflare und seine Dienstleister können Daten außerhalb des Europäischen Wirtschaftsraums (EWR) verarbeiten. Die ", { label: "Vereinbarung zur Auftragsverarbeitung", url: CLOUDFLARE_DPA_URL }, " enthält Garantien für diese Übermittlungen, gegebenenfalls Standardvertragsklauseln. Eine Kopie dieser Garantien kannst du auch per E-Mail anfordern."] },
      { heading: "Wie lange Daten gespeichert werden", body: ["Berichte verfallen nicht automatisch, damit du auch Jahre später darauf zurückkommen kannst. Sie bleiben gespeichert, solange sie dafür benötigt werden und der Dienst besteht, vorbehaltlich begründeter Löschanfragen. Ob sie weiterhin benötigt werden, wird mindestens einmal jährlich geprüft. Vorübergehend für den Upload gespeicherte Daten werden normalerweise innerhalb von zwei Stunden gelöscht. Gelöschte Daten können bis zu 30 Tage in Sicherungskopien verbleiben; diese sind nicht öffentlich zugänglich. Korrespondenz zu Datenschutzanfragen bleibt so lange gespeichert, wie sie zur Bearbeitung und deren Dokumentation benötigt wird. Dies wird jährlich überprüft. Technische Protokolle werden bis zu sieben Tage aufbewahrt. Cloudflare erläutert in seiner ", { label: "Datenschutzerklärung", url: CLOUDFLARE_PRIVACY_URL }, ", wie es Daten selbst zu Sicherheitszwecken nutzt und wie lange es sie speichert."] },
      { heading: "Kopien in deinem Browser", body: ["Für schnelleres Laden kann dein Browser eine gespeicherte Berichtskopie bis zu einer Woche verwenden, ohne nach Änderungen zu suchen. Das Löschen eines Berichts entfernt diese Kopien sowie offene Seiten, Screenshots oder Downloads nicht sofort. Deine Sprache und die Auswahl angehefteter Effekte werden im Browser gespeichert. Uploadfortschritt und Ergebnislink werden für die Dauer deiner Browsersitzung gespeichert. Du kannst diese Daten im Browser löschen. Die Website verwendet keine Werbe- oder Analyse-Cookies."] },
      { heading: "Deine Rechte und Anfragen", body: ["Über die E-Mail-Adresse oben kannst du Auskunft über deine Daten, Berichtigung, Löschung oder Einschränkung der Verarbeitung verlangen. Du kannst auch aus Gründen deiner besonderen Situation der Verarbeitung aufgrund berechtigter Interessen widersprechen. Es gelten die jeweiligen gesetzlichen Voraussetzungen. Nenne deine Plattform, den EU-/NA-Spielserver, deinen aktuellen und relevante frühere Gamertags sowie Berichtslinks, falls vorhanden. Ein Link ist nicht erforderlich. Zum Schutz der Spielerdaten kann eine Bestätigung erforderlich sein, dass du das betreffende Spielkonto kontrollierst. Dafür werden nur die notwendigen Informationen angefordert. Sende keine Passwörter und keine unaufgeforderten Ausweisdokumente. Anfragen werden unverzüglich, normalerweise innerhalb eines Monats, bearbeitet. Ist eine gesetzlich zulässige Verlängerung nötig, erfährst du den Grund innerhalb dieses Monats. Du kannst dich bei der schwedischen ", { label: "IMY", url: IMY_COMPLAINT_URL }, " oder einer anderen zuständigen Datenschutzbehörde beschweren, etwa an deinem Wohn- oder Arbeitsort."] },
    ],
  },
  es: {
    location: "Suecia", updated: "Última actualización", contact: "Operador y responsable del tratamiento",
    sections: [
      { heading: "Qué se sube", body: ["Pergaminos de Batalla permite guardar y compartir informes de combate de ESO en línea. Subirlos es opcional; el complemento funciona sin hacerlo. Los informes proceden del complemento del jugador que los sube y pueden incluir gamertags o nombres de personajes de otros jugadores, roles, estadísticas de combate, configuraciones, fechas y horas de combate, lugares del juego y títulos personalizados. También se incluyen la plataforma y el servidor de juego."] },
      { heading: "Para qué se usan los datos", body: ["Los datos se usan para conservar el historial de combate, analizar encuentros y compartir informes. La base jurídica son los intereses legítimos del artículo 6.1.f del RGPD: los intereses del operador y de los jugadores en estas actividades se ponderan frente a la privacidad y los derechos de las personas registradas. También se usa información técnica limitada para operar y proteger el servicio, y correspondencia para atender solicitudes de privacidad. Subir un informe no equivale a dar consentimiento en nombre de otros jugadores. Antes de subirlo, informa a los jugadores afectados de la subida y de este aviso. No hay publicidad, venta de datos personales ni decisiones automatizadas con efectos jurídicos o de importancia similar."] },
      { heading: "Quién puede acceder a los datos", body: ["Los informes no aparecen en un directorio público ni en un buscador de jugadores. Cualquiera que tenga el enlace puede ver, descargar o compartir el informe sin una cuenta. Cloudflare aloja el servicio y trata los informes y la información técnica, incluidas las direcciones IP, para prestarlo y protegerlo. Las direcciones IP no forman parte de los informes de combate. Cloudflare y sus proveedores de servicios pueden tratar datos fuera del Espacio Económico Europeo (EEE). Su ", { label: "acuerdo de tratamiento", url: CLOUDFLARE_DPA_URL }, " establece garantías para estas transferencias, incluidas las cláusulas contractuales tipo cuando correspondan. También puedes pedir una copia de estas garantías por correo."] },
      { heading: "Cuánto tiempo se conservan los datos", body: ["Los informes no caducan automáticamente, para que puedas volver a consultarlos años después. Se conservan mientras sean necesarios para ese fin y el servicio siga activo, sin perjuicio de las solicitudes de eliminación justificadas. Su necesidad se revisa al menos una vez al año. Los datos temporales de las subidas suelen eliminarse en dos horas. Los datos borrados pueden permanecer en copias de seguridad hasta 30 días; estas copias no son públicas. La correspondencia sobre privacidad se conserva mientras sea necesaria para resolver las solicitudes y documentar su gestión, con una revisión anual. Los registros técnicos se conservan hasta siete días. La ", { label: "política de privacidad de Cloudflare", url: CLOUDFLARE_PRIVACY_URL }, " explica cómo usa y conserva los datos para sus propios fines de seguridad."] },
      { heading: "Copias en tu navegador", body: ["Para cargar más rápido, el navegador puede reutilizar una copia guardada de un informe durante hasta una semana sin comprobar si hay cambios. Eliminar un informe no borra de inmediato esas copias ni las páginas abiertas, capturas o descargas. Tus preferencias de idioma y efectos fijados se guardan en el navegador. El progreso de la subida y el enlace resultante se guardan durante la sesión de navegación. Puedes borrar estos datos desde el navegador. El sitio no usa cookies publicitarias ni analíticas."] },
      { heading: "Tus derechos y solicitudes", body: ["Escribe al correo indicado para solicitar acceso a tus datos, su rectificación, supresión o la limitación de su uso. También puedes oponerte al tratamiento basado en intereses legítimos por motivos relacionados con tu situación particular. Se aplican las condiciones legales de cada derecho. Indica tu plataforma, servidor EU/NA, gamertag actual y los anteriores pertinentes, y enlaces a informes si los tienes; no se exige un enlace. Para proteger los datos de los jugadores, puede que se te pida confirmar que controlas la cuenta de juego correspondiente. Solo se pedirá la información necesaria para esa comprobación. No envíes contraseñas ni documentos de identidad que no se te hayan solicitado. Las solicitudes se atienden sin dilación indebida, normalmente en un mes. Si hace falta una prórroga permitida por la ley, se te explicará el motivo dentro de ese mes. Puedes reclamar ante la ", { label: "IMY", url: IMY_COMPLAINT_URL }, " sueca u otra autoridad de protección de datos competente, incluida la del lugar donde vives o trabajas."] },
    ],
  },
  fr: {
    location: "Suède", updated: "Dernière mise à jour", contact: "Exploitant et responsable du traitement",
    sections: [
      { heading: "Données envoyées", body: ["Parchemins de Bataille permet de conserver et de partager des rapports de combat ESO en ligne. L’envoi est facultatif ; l’extension fonctionne aussi sans envoyer de rapports. Les rapports proviennent de l’extension du joueur qui les envoie et peuvent contenir les gamertags ou noms de personnages d’autres joueurs, leurs rôles, statistiques de combat, builds, dates et heures des combats, lieux du jeu et titres personnalisés. La plateforme et le serveur de jeu sont également transmis."] },
      { heading: "Utilisation des données", body: ["Les données servent à conserver l’historique des combats, à les analyser et à partager des rapports. La base juridique est l’intérêt légitime prévu à l’article 6, paragraphe 1, point f du RGPD : les intérêts de l’exploitant et des joueurs liés à ces activités sont mis en balance avec la vie privée et les droits des personnes enregistrées. Des informations techniques limitées servent aussi au fonctionnement et à la sécurité du service, et la correspondance au traitement des demandes relatives aux données personnelles. Envoyer un rapport ne vaut pas consentement au nom des autres joueurs. Avant l’envoi, informez les joueurs concernés de cet envoi et de cette notice. Il n’y a ni publicité, ni vente de données personnelles, ni décision automatisée produisant des effets juridiques ou d’importance similaire."] },
      { heading: "Qui peut accéder aux données", body: ["Les rapports n’apparaissent ni dans un répertoire public ni dans une recherche de joueurs. Toute personne ayant le lien peut consulter, télécharger ou partager le rapport sans compte. Cloudflare héberge le service et traite les rapports ainsi que des informations techniques, dont les adresses IP, pour le fournir et le protéger. Les adresses IP ne font pas partie des rapports de combat. Cloudflare et ses prestataires peuvent traiter des données hors de l’Espace économique européen (EEE). Son ", { label: "accord de traitement", url: CLOUDFLARE_DPA_URL }, " prévoit des garanties pour ces transferts, notamment les clauses contractuelles types lorsqu’elles s’appliquent. Vous pouvez aussi demander une copie de ces garanties par courriel."] },
      { heading: "Durée de conservation", body: ["Les rapports n’expirent pas automatiquement, pour que vous puissiez les consulter des années plus tard. Ils sont conservés tant qu’ils sont nécessaires à cette fin et que le service fonctionne, sous réserve des demandes de suppression justifiées. La nécessité de les conserver est revue au moins une fois par an. Les données temporaires d’envoi sont normalement supprimées sous deux heures. Les données supprimées peuvent rester dans des sauvegardes jusqu’à 30 jours ; ces copies ne sont pas accessibles au public. La correspondance relative aux données personnelles est conservée aussi longtemps que nécessaire pour résoudre les demandes et documenter leur traitement, avec une révision annuelle. Les journaux techniques sont conservés jusqu’à sept jours. La ", { label: "politique de confidentialité de Cloudflare", url: CLOUDFLARE_PRIVACY_URL }, " explique comment l’entreprise utilise et conserve les données pour ses propres besoins de sécurité."] },
      { heading: "Copies dans votre navigateur", body: ["Pour accélérer le chargement, votre navigateur peut réutiliser une copie enregistrée d’un rapport pendant une semaine au maximum sans vérifier les changements. Supprimer un rapport n’efface pas immédiatement ces copies, les pages ouvertes, les captures d’écran ou les téléchargements. Vos préférences de langue et d’effets épinglés sont enregistrées dans votre navigateur. La progression de l’envoi et le lien obtenu sont conservés pour la durée de votre session de navigation. Vous pouvez effacer ces données dans votre navigateur. Le site n’utilise pas de cookies publicitaires ou analytiques."] },
      { heading: "Vos droits et demandes", body: ["Écrivez à l’adresse ci-dessus pour demander l’accès à vos données, leur rectification, leur effacement ou la limitation de leur utilisation. Vous pouvez aussi vous opposer au traitement fondé sur l’intérêt légitime pour des raisons tenant à votre situation particulière. Ces droits s’exercent dans les conditions prévues par la loi. Indiquez votre plateforme, serveur EU/NA, gamertag actuel et anciens gamertags pertinents, ainsi que les liens des rapports si vous en avez ; aucun lien n’est obligatoire. Pour protéger les données des joueurs, une confirmation que vous contrôlez le compte de jeu concerné peut être demandée. Seules les informations nécessaires à cette vérification seront demandées. N’envoyez pas de mot de passe ni de pièce d’identité non sollicitée. Les demandes sont traitées sans retard injustifié, normalement sous un mois. Si une prolongation autorisée par la loi est nécessaire, vous en serez informé avec son motif dans ce délai. Vous pouvez saisir l’", { label: "IMY", url: IMY_COMPLAINT_URL }, " suédoise ou une autre autorité de protection des données compétente, notamment dans votre pays de résidence ou de travail."] },
    ],
  },
  jp: {
    location: "スウェーデン", updated: "最終更新日", contact: "運営者・データ管理者",
    sections: [
      { heading: "アップロードされる情報", body: ["Battle Scrollsでは、ESOの戦闘レポートをオンラインで保存・共有できます。アップロードは任意で、行わなくてもアドオンは利用できます。レポートはアップロードしたプレイヤーのアドオンから取得され、他のプレイヤーのゲーマータグやキャラクター名、ロール、戦闘統計、ビルド、戦闘日時、ゲーム内の場所、独自のレポート名を含む場合があります。プラットフォームとゲームサーバーも送信されます。"] },
      { heading: "情報の利用目的", body: ["情報は、戦闘履歴の保存、戦闘の分析、レポートの共有に利用します。法的根拠はGDPR第6条1項(f)の正当な利益です。これらの活動に関する運営者とプレイヤーの利益を、記録される人々のプライバシーや権利と比較して判断します。また、サービスの運営と安全確保のために必要な範囲の技術情報を利用し、プライバシーに関する請求への対応に連絡内容を利用します。レポートのアップロードは、他のプレイヤーに代わって同意することにはなりません。アップロードする前に、対象のプレイヤーにアップロードと本ポリシーについて知らせてください。広告、個人データの販売、法的または同程度の重大な影響を及ぼす自動意思決定は行いません。"] },
      { heading: "情報にアクセスできる人", body: ["レポートは公開一覧やプレイヤー検索には表示されません。リンクを持つ人は誰でも、アカウントなしでレポートを閲覧、ダウンロード、共有できます。Cloudflareがサービスをホストし、提供と安全確保のためにレポートやIPアドレスを含む技術情報を処理します。IPアドレスは戦闘レポートには含まれません。Cloudflareとその委託先は、欧州経済領域（EEA）の外でデータを処理する場合があります。同社の", { label: "データ処理契約", url: CLOUDFLARE_DPA_URL }, "には、該当する場合の標準契約条項など、データ移転の保護措置が定められています。これらの保護措置の写しはメールでも請求できます。"] },
      { heading: "保存期間", body: ["何年も後に振り返れるよう、レポートに自動の保存期限はありません。この目的に必要でサービスが継続する間保存しますが、正当な削除請求には対応します。保存の必要性は少なくとも年1回見直します。アップロードに使う一時的なデータは通常2時間以内に削除します。削除済みデータはバックアップに最長30日間残る場合がありますが、このコピーは一般には公開されません。プライバシーに関する連絡内容は、請求への対応とその記録に必要な間保存し、年1回見直します。技術ログの保存期間は最長7日間です。Cloudflare自身が安全確保のために行うデータの利用と保存については、同社の", { label: "プライバシーポリシー", url: CLOUDFLARE_PRIVACY_URL }, "に説明されています。"] },
      { heading: "ブラウザ内のコピー", body: ["読み込みを速くするため、ブラウザは保存済みのレポートを最長1週間、変更の有無を確認せずに表示する場合があります。レポートを削除しても、これらのコピーや開いたままのページ、スクリーンショット、ダウンロード済みのデータを直ちに消すことはできません。言語とピン留めした効果の設定はブラウザに保存されます。アップロードの進行状況と取得したリンクは、ブラウザの利用セッション中保存されます。これらの情報はブラウザから自分で消去できます。広告やアクセス解析用のCookieは使用しません。"] },
      { heading: "権利と請求方法", body: ["上記メールアドレスから、ご自身のデータへのアクセス、訂正、削除、利用の制限を請求できます。また、ご自身の状況に関する理由により、正当な利益に基づく処理に異議を申し立てることもできます。各権利には法令上の条件が適用されます。プラットフォーム、EU/NAゲームサーバー、現在と関係する過去のゲーマータグ、分かる場合はレポートのリンクをお知らせください。リンクは必須ではありません。プレイヤーのデータを守るため、対象のゲームアカウントを管理していることの確認をお願いする場合があります。その確認に必要な情報のみを求めます。パスワードや、求められていない身分証明書を送らないでください。請求には不当な遅延なく、通常1か月以内に対応します。法令上認められる延長が必要な場合は、その理由を同期間内にお知らせします。スウェーデンの", { label: "IMY", url: IMY_COMPLAINT_URL }, "、または居住地や勤務先などを管轄するデータ保護機関に苦情を申し立てることもできます。"] },
    ],
  },
  ru: {
    location: "Швеция", updated: "Обновлено", contact: "Владелец сервиса и оператор персональных данных",
    sections: [
      { heading: "Какие данные загружаются", body: ["«Боевые Свитки» позволяют сохранять отчёты о боях ESO в интернете и делиться ими. Загрузка добровольна: дополнение работает и без неё. Отчёты поступают из дополнения загрузившего их игрока и могут содержать игровые имена учётных записей или персонажей других игроков, роли, боевую статистику, сборки, время и места боёв в игре, а также заданные игроком названия отчётов. Вместе с отчётом передаются платформа и игровой сервер."] },
      { heading: "Для чего нужны данные", body: ["Данные используются для сохранения истории боёв, их анализа и обмена отчётами. Правовое основание — законные интересы по статье 6(1)(f) GDPR: интересы оператора и игроков, связанные с этими целями, сопоставляются с правом на частную жизнь и другими правами людей, чьи данные записаны. Ограниченные технические сведения также нужны для работы и защиты сервиса, а переписка — для обработки запросов о персональных данных. Загрузка отчёта не означает согласия от имени других игроков. Перед загрузкой сообщите затронутым игрокам о ней и об этой политике. В сервисе нет рекламы, продажи персональных данных или автоматизированных решений с юридическими либо сопоставимыми существенными последствиями."] },
      { heading: "Кто может получить доступ к данным", body: ["Отчёты не появляются в общедоступном каталоге или поиске по игрокам. Любой, у кого есть ссылка, может открыть отчёт, скачать его или поделиться им без учётной записи. Cloudflare размещает сервис и обрабатывает отчёты и технические сведения, включая IP-адреса, для его работы и защиты. IP-адреса не входят в боевые отчёты. Cloudflare и его поставщики услуг могут обрабатывать данные за пределами Европейской экономической зоны (ЕЭЗ). ", { label: "Соглашение об обработке данных", url: CLOUDFLARE_DPA_URL }, " предусматривает гарантии при такой передаче, включая стандартные договорные положения, когда они применимы. Копию этих гарантий также можно запросить по электронной почте."] },
      { heading: "Сроки хранения", body: ["Отчёты не удаляются автоматически, чтобы к ним можно было вернуться спустя годы. Они хранятся, пока нужны для этой цели и сервис работает, с учётом обоснованных запросов на удаление. Необходимость хранения пересматривается не реже раза в год. Временные данные загрузок обычно удаляются в течение двух часов. Удалённые данные могут оставаться в резервных копиях до 30 дней; эти копии недоступны посетителям. Переписка по вопросам персональных данных хранится, пока нужна для решения запросов и подтверждения их обработки, с ежегодным пересмотром необходимости хранения. Технические журналы хранятся до семи дней. Использование и хранение данных для собственных целей безопасности Cloudflare описывает в своей ", { label: "политике конфиденциальности", url: CLOUDFLARE_PRIVACY_URL }, "."] },
      { heading: "Копии в браузере", body: ["Чтобы отчёт открывался быстрее, браузер может до недели показывать сохранённую копию без проверки изменений. Удаление отчёта не позволяет немедленно стереть эти копии, открытые страницы, скриншоты или скачанные файлы. Выбранный язык и закреплённые эффекты сохраняются в браузере. Ход загрузки и полученная ссылка сохраняются на время сеанса браузера. Эти данные можно удалить самостоятельно в браузере. Сайт не использует рекламные или аналитические cookie."] },
      { heading: "Ваши права и обращения", body: ["Напишите на адрес выше, чтобы запросить доступ к своим данным, их исправление, удаление или ограничение обработки. Вы также можете возразить против обработки на основании законных интересов по причинам, связанным с вашей конкретной ситуацией. Права действуют при установленных законом условиях. Укажите платформу, игровой сервер EU/NA, текущее и относящиеся к запросу прежние имена учётной записи, а также ссылки на отчёты, если они есть. Ссылка не обязательна. Для защиты данных игроков может потребоваться подтверждение, что вы управляете соответствующей игровой учётной записью. Будут запрошены только необходимые для этой проверки сведения. Не присылайте пароли. Документы, удостоверяющие личность, отправляйте только по запросу. Обращения обрабатываются без неоправданной задержки, обычно в течение месяца. Если потребуется допустимое законом продление, о его причине будет сообщено в течение этого месяца. Вы можете пожаловаться в шведский орган ", { label: "IMY", url: IMY_COMPLAINT_URL }, " или другой компетентный орган защиты данных, в том числе по месту жительства или работы."] },
    ],
  },
  zh: {
    location: "瑞典", updated: "最后更新", contact: "运营者与数据控制者",
    sections: [
      { heading: "上传哪些数据", body: ["Battle Scrolls 让你能够在线保存和分享 ESO 战斗报告。上传是自愿的，不上传也能使用插件。报告来自上传者的插件，可能包含其他玩家的游戏账号名或角色名、职责、战斗统计、配装、战斗时间、游戏内地点及自定义报告标题。上传内容还包括游戏平台和服务器。"] },
      { heading: "数据用途", body: ["数据用于保存战斗历史、分析战斗和分享报告。法律依据为 GDPR 第 6(1)(f) 条规定的合法利益：运营者和玩家开展这些活动的利益，会与被记录者的隐私和权利进行权衡。服务还使用少量技术信息来维持运行和保障安全，并使用往来邮件处理隐私请求。上传报告不等于代表其他玩家同意处理其数据。上传前，请告知相关玩家此次上传及本政策。本服务不投放广告、不出售个人数据，也不作出具有法律效力或类似重大影响的自动化决策。"] },
      { heading: "谁能访问数据", body: ["报告不会出现在公开目录或玩家搜索结果中。任何持有报告链接的人都能在无需账号的情况下查看、下载或分享报告。Cloudflare 托管本服务，并处理报告和包括 IP 地址在内的技术信息，以提供服务和保障安全。IP 地址不属于战斗报告的内容。Cloudflare 及其服务提供商可能在欧洲经济区（EEA）以外处理数据。其", { label: "数据处理协议", url: CLOUDFLARE_DPA_URL }, "为这些传输提供保障，包括在适用时使用标准合同条款。你也可以通过邮件索取这些保障措施的副本。"] },
      { heading: "保存期限", body: ["报告不会自动到期，方便你在多年后再次查阅。只要仍为此目的所需且服务仍在运营，就会保留，同时会处理有正当理由的删除请求。至少每年复查一次保存的必要性。上传所用的临时数据通常会在两小时内删除。已删除的数据可能在备份中保留最多 30 天，这些备份不对公众开放。隐私请求的往来邮件会在解决请求及记录处理情况所需的期间内保留，并每年复查。技术日志最多保留七天。Cloudflare 在其", { label: "隐私政策", url: CLOUDFLARE_PRIVACY_URL }, "中说明自身为安全目的如何使用和保存数据。"] },
      { heading: "浏览器中的副本", body: ["为加快加载，浏览器可能在最多一周内重复使用已保存的报告，而不检查是否有变化。删除报告无法立即清除这些副本、已打开的页面、截图或下载的文件。语言和置顶效果偏好保存在浏览器中。上传进度和生成的链接会在浏览会话期间保存。你可以在浏览器中自行清除这些记录。本网站不使用广告或分析 Cookie。"] },
      { heading: "你的权利与请求", body: ["请发送邮件至上方地址，申请访问、更正、删除你的数据或限制其使用。你也可以基于自身具体情况，反对以合法利益为依据的数据处理。这些权利适用法律规定的条件。请提供平台、EU/NA 游戏服务器、当前及相关曾用游戏账号名，如有报告链接也请提供；链接并非必需。为保护玩家数据，可能会请你确认自己控制着相关游戏账号。只会索取完成这项核验所需的信息。请勿发送密码，也不要发送未被要求提供的身份证件。请求将得到及时处理，通常在一个月内完成。如需依法延长处理时间，会在该月内告知原因。你可向瑞典 ", { label: "IMY", url: IMY_COMPLAINT_URL }, " 或其他有管辖权的数据保护机构投诉，包括居住地或工作所在地的机构。"] },
    ],
  },
};
